[package]
name = "definition"
version = "0.1.0"
authors = ["Kneeboard Notes <kneeboardnotes@outlook.com>"]
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
arbitrary = { version = "1.3.0", optional = true, features = ["derive"] }