[package]
name = "core"
version = "0.1.0"
authors = ["Kneeboard Notes <kneeboardnotes@outlook.com>"]
edition = "2021"

[dependencies]
pdf = { path = "../pdf" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"